FROM node:18-alpine as build
WORKDIR /src
COPY . .
RUN npm i
RUN npm run build-dev

FROM nginx:stable-alpine
COPY .nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/build /usr/share/nginx/html
