FROM node:18-alpine as build
WORKDIR /src
COPY . .
RUN npm ci
RUN npm run build

RUN apk add dos2unix
RUN cat create-env-config.sh | dos2unix > create-env-config.sh.tmp
RUN mv create-env-config.sh.tmp create-env-config.sh
RUN chmod +x create-env-config.sh


FROM nginx:stable-alpine
COPY .nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/build /usr/share/nginx/html
COPY --from=build /src/create-env-config.sh /docker-entrypoint.d/

HEALTHCHECK --interval=30s --timeout=30s --start-period=30s --retries=3 CMD curl -f http://localhost || exit 1
