import IBreakTimeNotificationOverviewController from "./IBreakTimeNotificationOverviewController";

export default class BreakTimeNotificationOverviewController
  implements IBreakTimeNotificationOverviewController {}
