import INarrativeFrameworkLoadingScreenContainerController from "./INarrativeFrameworkLoadingScreenContainerController";

export default class NarrativeFrameworkLoadingScreenContainerController
  implements INarrativeFrameworkLoadingScreenContainerController {}
