const BUILDER_TYPES = {
  IPresentationDirector: Symbol("IPresentationDirector"),
  ISpaceBuilder: Symbol("ISpaceBuilder"),
  IElementBuilder: Symbol("IElementBuilder"),
  IDoorBuilder: Symbol("IDoorBuilder"),
  IScorePanelBuilder: Symbol("IScorePanelBuilder"),
  IMoodleLoginFormBuilder: Symbol("IMoodleLoginFormBuilder"),
  IElementModalBuilder: Symbol("IElementModalBuilder"),
  IAvatarBuilder: Symbol("IAvatarBuilder"),
  IElementsDropdownBuilder: Symbol("IElementsDropdownBuilder"),
  IModalManagerBuilder: Symbol("IModalManagerBuilder"),
  IMoodleLoginButtonBuilder: Symbol("IMoodleLoginButtonBuilder"),
  IBottomTooltipBuilder: Symbol("IBottomTooltipBuilder"),
  IDebugPanelBuilder: Symbol("IDebugPanelBuilder"),
  IWorldNamePanelBuilder: Symbol("IWorldNamePanelBuilder"),
  ILoadSpaceButtonBuilder: Symbol("ILoadSpaceButtonBuilder"),
  IFullscreenSwitchBuilder: Symbol("IFullscreenSwitchBuilder"),
  ISpaceGoalPanelBuilder: Symbol("ISpaceGoalPanelBuilder"),
  IHeaderBarBuilder: Symbol("IHeaderBarBuilder"),
  ISpaceSelectionBuilder: Symbol("ISpaceSelectionBuilder"),
  IDetailSectionBuilder: Symbol("IDetailSectionBuilder"),
  ISpaceCompletionModalBuilder: Symbol("ISpaceCompletionModalBuilder"),
  IWorldCompletionModalBuilder: Symbol("IWorldCompletionModalBuilder"),
};

export default BUILDER_TYPES;
