const BUILDER_TYPES = {
  IPresentationDirector: Symbol("IPresentationDirector"),
  ILearningSpaceBuilder: Symbol("ILearningSpaceBuilder"),
  ILearningElementBuilder: Symbol("ILearningElementBuilder"),
  IDoorBuilder: Symbol("IDoorBuilder"),
  IWindowBuilder: Symbol("IWindowBuilder"),
  ILearningElementModalBuilder: Symbol("ILearningElementModalBuilder"),
  IAvatarBuilder: Symbol("IAvatarBuilder"),
  IModalManagerBuilder: Symbol("IModalManagerBuilder"),
  ISignInAndOutComponentBuilder: Symbol("ISignInAndOutComponentBuilder"),
  IBottomTooltipBuilder: Symbol("IBottomTooltipBuilder"),
  ILearningWorldNamePanelBuilder: Symbol("ILearningWorldNamePanelBuilder"),
  ILoadLearningSpaceButtonBuilder: Symbol("ILoadLearningSpaceButtonBuilder"),
  IFullscreenSwitchBuilder: Symbol("IFullscreenSwitchBuilder"),
  ILearningSpaceGoalPanelBuilder: Symbol("ILearningSpaceGoalPanelBuilder"),
  IHeaderBarBuilder: Symbol("IHeaderBarBuilder"),
  ILearningSpaceSelectionBuilder: Symbol("ILearningSpaceSelectionBuilder"),
  ILearningSpaceDetailBuilder: Symbol("ILearningSpaceDetailBuilder"),
  ILearningWorldDetailBuilder: Symbol("ILearningWorldDetailBuilder"),
  ILearningWorldCompletionModalBuilder: Symbol(
    "ILearningWorldCompletionModalBuilder",
  ),
  IMenuBarBuilder: Symbol("IMenuBarBuilder"),
  IUseGuideBuilder: Symbol("IUseGuideBuilder"),
  ILearningWorldMenuButtonBuilder: Symbol("ILearningWorldMenuButtonBuilder"),
  IAvatarCameraBuilder: Symbol("IAvatarCameraBuilder"),
  IExitModalBuilder: Symbol("IExitModalBuilder"),
  ILearningWorldSelectionBuilder: Symbol("ILearningWorldSelectionBuilder"),
  IAmbienceBuilder: Symbol("IAmbienceBuilder"),
  ILearningSpaceScorePanelBuilder: Symbol("ILearningSpaceScorePanelBuilder"),
  ILearningWorldScorePanelBuilder: Symbol("ILearningWorldScorePanelBuilder"),
  IDecorationBuilder: Symbol("IDecorationBuilder"),
  IStandInDecorationBuilder: Symbol("IStandInDecorationBuilder"),
  IHelpDeskModalBuilder: Symbol("IHelpDeskModalBuilder"),
  IHelpDeskButtonBuilder: Symbol("IHelpDeskButtonBuilder"),
  IAdaptivityElementBuilder: Symbol("IAdaptivityElementBuilder"),
  IBreakTimeNotificationBuilder: Symbol("IBreakTimeNotificationBuilder"),
  ILoadingScreenBuilder: Symbol("ILoadingScreenBuilder"),
  IStoryElementBuilder: Symbol("IStoryElementBuilder"),
  IStoryNPCBuilder: Symbol("IStoryNPCBuilder"),
  ICookieModalBuilder: Symbol("ICookieModalBuilder"),
  IReturnHomeModalBuilder: Symbol("IReturnHomeModalBuilder"),
  IControlsExplanationModalBuilder: Symbol("IControlsExplanationModalBuilder"),
  IMoodleButtonBuilder: Symbol("IMoodleButtonBuilder"),
  IBreakTimeNotificationOverviewBuilder: Symbol(
    "IBreakTimeNotificationOverviewBuilder",
  ),
  IAvatarEditorBuilder: Symbol("IAvatarEditorBuilder"),
  IAvatarEditorPreviewCameraBuilder: Symbol(
    "IAvatarEditorPreviewCameraBuilder",
  ),
  IAvatarEditorPreviewBuilder: Symbol("IAvatarEditorPreviewBuilder"),
  IAvatarEditorPreviewModelBuilder: Symbol("IAvatarEditorPreviewModelBuilder"),
  INarrativeFrameworkBuilder: Symbol("INarrativeFrameworkBuilder"),
  INarrativeFrameworkLoadingScreenContainerBuilder: Symbol(
    "INarrativeFrameworkLoadingScreenContainerBuilder",
  ),
  INarrativeFrameworkLearningSpaceContainerBuilder: Symbol(
    "INarrativeFrameworkLearningSpaceContainerBuilder",
  ),
};

export default BUILDER_TYPES;
