const BUILDER_TYPES = {
  IPresentationDirector: Symbol("IPresentationDirector"),
  ISpaceBuilder: Symbol("ISpaceBuilder"),
  IElementBuilder: Symbol("IElementBuilder"),
  IDoorBuilder: Symbol("IDoorBuilder"),
  IScorePanelBuilder: Symbol("IScorePanelBuilder"),
  ILoginModalBuilder: Symbol("ILoginModalBuilder"),
  IElementModalBuilder: Symbol("IElementModalBuilder"),
  IAvatarBuilder: Symbol("IAvatarBuilder"),
  IElementsDropdownBuilder: Symbol("IElementsDropdownBuilder"),
  IModalManagerBuilder: Symbol("IModalManagerBuilder"),
  ILoginButtonBuilder: Symbol("ILoginButtonBuilder"),
  IBottomTooltipBuilder: Symbol("IBottomTooltipBuilder"),
  IWorldNamePanelBuilder: Symbol("IWorldNamePanelBuilder"),
  ILoadSpaceButtonBuilder: Symbol("ILoadSpaceButtonBuilder"),
  IFullscreenSwitchBuilder: Symbol("IFullscreenSwitchBuilder"),
  ISpaceGoalPanelBuilder: Symbol("ISpaceGoalPanelBuilder"),
  IHeaderBarBuilder: Symbol("IHeaderBarBuilder"),
  ISpaceSelectionBuilder: Symbol("ISpaceSelectionBuilder"),
  IDetailSectionBuilder: Symbol("IDetailSectionBuilder"),
  ISpaceCompletionModalBuilder: Symbol("ISpaceCompletionModalBuilder"),
  IWorldCompletionModalBuilder: Symbol("IWorldCompletionModalBuilder"),
  IMenuBarBuilder: Symbol("IMenuBarBuilder"),
  IUseGuideBuilder: Symbol("IUseGuideBuilder"),
  IWorldMenuButtonBuilder: Symbol("IWorldMenuButtonBuilder"),
  IAvatarCameraBuilder: Symbol("IAvatarCameraBuilder"),
  IExitModalBuilder: Symbol("IExitModalBuilder"),
};

export default BUILDER_TYPES;
