import INarrativeFrameworkWorldCompletionModalContainerController from "./INarrativeFrameworkWorldCompletionModalContainerController";

export default class NarrativeFrameworkWorldCompletionModalContainerController
  implements INarrativeFrameworkWorldCompletionModalContainerController {}
