const CORE_TYPES = {
  ICore: Symbol("ICore"),
  ICoreFactory: Symbol("ICoreFactory"),
  IDataAccess: Symbol("IDataAccess"),
  IEntityFactory: Symbol("IEntityFactory"),
  IPresentation: Symbol("IPresentation"),
  IEngineManager: Symbol("IEngineManager"),
  ISceneView: Symbol("ISceneView"),
  ISceneController: Symbol("ISceneController"),
  ICreateSceneClass: Symbol("ICreateSceneClass"),
  ILearningRoomController: Symbol("ILearningRoomController"),
  ILearningRoomView: Symbol("ILearningRoomView"),
  ILearningElementView: Symbol("ILearingElementView"),
  ILearingElementPresenter: Symbol("ILearingElementPresenter"),
  ILearningElementFactory: Symbol("ILearningElementFactory"),
  IEntityManager: Symbol("IEntityManager"),
  ICoreRenderer: Symbol("ICoreRenderer"),
  ILearningElementPanelPresenter: Symbol("ILearningElementPanelPresenter"),
  ILearningElementPanelViewModel: Symbol("ILearningElementPanelViewModel"),
  IViewModelProvider: Symbol("IViewModelProvider"),
  ILoadWorldController: Symbol("ILoadWorldController"),
  ILearningWorldPort: Symbol("ILearningWorldPort"),
  IEntityContainer: Symbol("IEntityContainer"),
  ILearningRoomPort: Symbol("ILearningRoomPort"),
  IPresentationDirector: Symbol("IPresentationDirector"),
  ILearningRoomBuilder: Symbol("ILearningRoomBuilder"),
  ILearningElementBuilder: Symbol("ILearningElementBuilder"),
  IBackend: Symbol("IBackend"),
  ILearningElementPort: Symbol("ILearningElementPort"),
};

export default CORE_TYPES;
