let CORE_TYPES = {
  ICore: Symbol("ICore"),
  ICoreFactory: Symbol("ICoreFactory"),
  IDataAccess: Symbol("IDataAccess"),
  IEntityFactory: Symbol("IEntityFactory"),
  IPresentation: Symbol("IPresentation"),
  IEngineManager: Symbol("IEngineManager"),
  ISceneView: Symbol("ISceneView"),
  ISceneController: Symbol("ISceneController"),
  ICreateSceneClass: Symbol("ICreateSceneClass"),
  IRoomConfigurator: Symbol("IRoomConfigurator"),
  IRoomController: Symbol("IRoomController"),
  IRoomView: Symbol("IRoomView"),
  IMoodle: Symbol("IMoodle"),
  IMoodleDataAccess: Symbol("IMoodleDataAccess"),
  MoodleData: Symbol("MoodleData"),
  ILearingElementView: Symbol("ILearingElementView"),
  ILearingElementPresenter: Symbol("ILearingElementPresenter"),
  ILearningElementFactory: Symbol("ILearningElementFactory"),
  IEntityManager: Symbol("IEntityManager"),
  ICoreRenderer: Symbol("ICoreRenderer"),
  ILearningElementPanelPresenter: Symbol("ILearningElementPanelPresenter"),
  ILearningElementPanelViewModel: Symbol("ILearningElementPanelViewModel"),
  IViewModelProvider: Symbol("IViewModelProvider"),
  ILoadWorld: Symbol("ILoadWorld"),
  ILoadWorldController: Symbol("ILoadWorldController"),
  ILearningWorldPort: Symbol("ILearningWorldPort"),
  IEntityContainer: Symbol("IEntityContainer"),
};

export default CORE_TYPES;
