import AWT from "../../Types/AWT";

const CampusAB_EatingArea: AWT = {
  fileVersion: "0.4",
  amgVersion: "1.0",
  author: "Theme Test",
  language: "de",
  world: {
    worldName: "Campus AB - Eating Area",
    worldDescription:
      "Test world for CAMPUSASCHAFFENBURG_EATINGAREA theme with all floor plans",
    worldGoals: [
      "Test CAMPUSASCHAFFENBURG_EATINGAREA theme",
      "Verify all floor plans",
      "Check rendering",
    ],
    evaluationLink: "https://www.th-ab.de",
    topics: [
      {
        topicId: 1201,
        topicName: "Campus AB - Eating Area Test",
        topicContents: [1, 2, 3, 4, 5],
      },
    ],
    spaces: [
      {
        spaceId: 1,
        spaceName: "Campus AB - Eating Area - R6 Floor Plan",
        spaceDescription: "Rectangle 20x20 with 6 learning elements",
        requiredPointsToComplete: 0,
        spaceSlotContents: [1, null, 2, 3, 4, null],
        requiredSpacesToEnter: "",
        spaceGoals: ["Test R6 floor plan"],
        spaceTemplate: "R_20X20_6L",
        spaceTemplateStyle: "CAMPUSASCHAFFENBURG_EATINGAREA",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Welcome to the R6 floor plan test for Campus AB - Eating Area",
            ],
            elementModel: "a_npc_defaultnpc",
          },
          outroStory: {
            storyTexts: ["R6 floor plan test completed"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 2,
        spaceName: "Campus AB - Eating Area - R8 Floor Plan",
        spaceDescription: "Rectangle 20x30 with 8 learning elements",
        requiredPointsToComplete: 0,
        spaceSlotContents: [null, 1, 2, 3, null, 4, 5, null],
        requiredSpacesToEnter: "1",
        spaceGoals: ["Test R8 floor plan"],
        spaceTemplate: "R_20X30_8L",
        spaceTemplateStyle: "CAMPUSASCHAFFENBURG_EATINGAREA",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Welcome to the R8 floor plan test for Campus AB - Eating Area",
            ],
            elementModel: "a_npc_defaultnpc",
          },
          outroStory: {
            storyTexts: ["R8 floor plan test completed"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 3,
        spaceName: "Campus AB - Eating Area - L10 Floor Plan",
        spaceDescription: "L-shaped 32x31 with 10 learning elements",
        requiredPointsToComplete: 0,
        spaceSlotContents: [null, null, 1, 2, null, 3, 4, null, 5, null],
        requiredSpacesToEnter: "2",
        spaceGoals: ["Test L10 floor plan"],
        spaceTemplate: "L_32X31_10L",
        spaceTemplateStyle: "CAMPUSASCHAFFENBURG_EATINGAREA",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Welcome to the L10 floor plan test for Campus AB - Eating Area",
            ],
            elementModel: "a_npc_defaultnpc",
          },
          outroStory: {
            storyTexts: ["L10 floor plan test completed"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 4,
        spaceName: "Campus AB - Eating Area - T13 Floor Plan",
        spaceDescription: "T-shaped 40x32 with 13 learning elements",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          null,
          1,
          null,
          2,
          null,
          null,
          null,
          null,
          3,
          4,
          null,
          5,
          6,
        ],
        requiredSpacesToEnter: "3",
        spaceGoals: ["Test T13 floor plan"],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "CAMPUSASCHAFFENBURG_EATINGAREA",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Welcome to the T13 floor plan test for Campus AB - Eating Area",
            ],
            elementModel: "a_npc_defaultnpc",
          },
          outroStory: {
            storyTexts: ["T13 floor plan test completed"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 5,
        spaceName: "Campus AB - Eating Area - D15 Floor Plan",
        spaceDescription: "D-shaped 42x36 with 15 learning elements",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          null,
          1,
          null,
          2,
          null,
          3,
          null,
          null,
          4,
          5,
          null,
          null,
          6,
          null,
          null,
        ],
        requiredSpacesToEnter: "4",
        spaceGoals: ["Test D15 floor plan"],
        spaceTemplate: "D_40X37_15L",
        spaceTemplateStyle: "CAMPUSASCHAFFENBURG_EATINGAREA",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Welcome to the D15 floor plan test for Campus AB - Eating Area",
            ],
            elementModel: "a_npc_defaultnpc",
          },
          outroStory: {
            storyTexts: ["D15 floor plan test completed"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
    ],
    elements: [
      {
        $type: "LearningElement",
        elementId: 1,
        elementName: "Test H5P Element",
        elementDescription: "H5P element for testing",
        elementGoals: ["Test goal"],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 100,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 2,
        elementName: "Test Text Element",
        elementDescription: "Text element for testing",
        elementGoals: ["Test goal"],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 0,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 3,
        elementName: "Test Image Element",
        elementDescription: "Image element for testing",
        elementGoals: ["Test goal"],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 0,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 4,
        elementName: "Test Video Element",
        elementDescription: "Video element for testing",
        elementGoals: ["Test goal"],
        elementCategory: "video",
        elementFileType: "mp4",
        elementMaxScore: 0,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 5,
        elementName: "Test PDF Element",
        elementDescription: "PDF element for testing",
        elementGoals: ["Test goal"],
        elementCategory: "text",
        elementFileType: "pdf",
        elementMaxScore: 0,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 6,
        elementName: "Test Adaptivity Element",
        elementDescription: "Adaptivity element for testing",
        elementGoals: ["Test goal"],
        elementCategory: "adaptivity",
        elementFileType: "json",
        elementMaxScore: 100,
        elementModel: "",
      },
    ],
  },
};

export default CampusAB_EatingArea;
