import AWT from "../Types/AWT";

/* istanbul ignore next */
const LEModelTestAWT: AWT = {
  fileVersion: "0.1",
  world: {
    worldName: "New World",
    topics: [],
    spaces: [
      {
        spaceId: 0,
        spaceName: "Text Models",
        spaceSlotContents: [0, 1, 2, 3, 4],
        requiredPointsToComplete: 0,
        requiredSpacesToEnter: "",
        spaceTemplate: "D_40X37_15L",
        spaceTemplateStyle: "Campus",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
      {
        spaceId: 1,
        spaceName: "Image Models",
        spaceSlotContents: [5, 6, 7, 8, 9, 10, 11, 12, 13],
        requiredPointsToComplete: 0,
        requiredSpacesToEnter: "",
        spaceTemplate: "D_40X37_15L",
        spaceTemplateStyle: "Campus",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
      {
        spaceId: 2,
        spaceName: "Video Models",
        spaceSlotContents: [14, 15, 16],
        requiredPointsToComplete: 0,
        requiredSpacesToEnter: "",
        spaceTemplate: "D_40X37_15L",
        spaceTemplateStyle: "Campus",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
      {
        spaceId: 3,
        spaceName: "H5P Models",
        spaceSlotContents: [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        requiredPointsToComplete: 0,
        requiredSpacesToEnter: "",
        spaceTemplate: "D_40X37_15L",
        spaceTemplateStyle: "Campus",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
    ],
    elements: [
      {
        $type: "LearningElement",
        elementId: 0,
        elementName: "l_text_bookshelf_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 1,
        elementModel: "l_text_bookshelf_1",
      },
      {
        $type: "LearningElement",
        elementId: 1,
        elementName: "l_text_bookshelf_2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 1,
        elementModel: "l_text_bookshelf_2",
      },
      {
        $type: "LearningElement",
        elementId: 2,
        elementName: "l_text_comicshelfbig_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 1,
        elementModel: "l_text_comicshelfbig_1",
      },
      {
        $type: "LearningElement",
        elementId: 3,
        elementName: "l_text_comicshelfsmall_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 1,
        elementModel: "l_text_comicshelfsmall_1",
      },
      {
        $type: "LearningElement",
        elementId: 4,
        elementName: "l_text_libraryshelf_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 1,
        elementModel: "l_text_libraryshelf_1",
      },
      {
        $type: "LearningElement",
        elementId: 5,
        elementName: "l_image_painting_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_painting_1",
      },
      {
        $type: "LearningElement",
        elementId: 6,
        elementName: "l_image_painting_2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_painting_2",
      },
      {
        $type: "LearningElement",
        elementId: 7,
        elementName: "l_image_paintingeasel_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_paintingeasel_1",
      },
      {
        $type: "LearningElement",
        elementId: 8,
        elementName: "l_image_gameposter_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_gameposter_1",
      },
      {
        $type: "LearningElement",
        elementId: 9,
        elementName: "l_image_gameposter_2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_gameposter_2",
      },
      {
        $type: "LearningElement",
        elementId: 10,
        elementName: "l_image_cardboardcutout_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_cardboardcutout_1",
      },
      {
        $type: "LearningElement",
        elementId: 11,
        elementName: "l_image_sciencegeo_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_sciencegeo_1",
      },
      {
        $type: "LearningElement",
        elementId: 12,
        elementName: "l_image_sciencebio_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_sciencebio_1",
      },
      {
        $type: "LearningElement",
        elementId: 13,
        elementName: "l_image_sciencewhiteboard_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_sciencewhiteboard_1",
      },
      {
        $type: "LearningElement",
        elementId: 14,
        elementName: "l_video_television_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_television_1",
      },
      {
        $type: "LearningElement",
        elementId: 15,
        elementName: "l_video_vrdesk_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_vrdesk_1",
      },
      {
        $type: "LearningElement",
        elementId: 16,
        elementName: "l_video_movieprojector_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_movieprojector_1",
      },
      {
        $type: "LearningElement",
        elementId: 17,
        elementName: "l_h5p_blackboard_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackboard_1",
      },
      {
        $type: "LearningElement",
        elementId: 18,
        elementName: "l_h5p_deskpc_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_deskpc_1",
      },
      {
        $type: "LearningElement",
        elementId: 19,
        elementName: "l_h5p_drawingtable_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_drawingtable_1",
      },
      {
        $type: "LearningElement",
        elementId: 20,
        elementName: "l_h5p_slotmachine_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_slotmachine_1",
      },
      {
        $type: "LearningElement",
        elementId: 21,
        elementName: "l_h5p_greyslotmachine_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_greyslotmachine_1",
      },
      {
        $type: "LearningElement",
        elementId: 22,
        elementName: "l_h5p_redslotmachine_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_redslotmachine_1",
      },
      {
        $type: "LearningElement",
        elementId: 23,
        elementName: "l_h5p_purpleslotmachine_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_purpleslotmachine_1",
      },
      {
        $type: "LearningElement",
        elementId: 24,
        elementName: "l_h5p_blackslotmachine_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackslotmachine_1",
      },
      {
        $type: "LearningElement",
        elementId: 25,
        elementName: "l_h5p_deskpc_2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_deskpc_2",
      },
      {
        $type: "LearningElement",
        elementId: 26,
        elementName: "l_h5p_blackboard_2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackboard_2",
      },
      {
        $type: "LearningElement",
        elementId: 27,
        elementName: "l_h5p_deskpc_3",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_deskpc_3",
      },
      {
        $type: "LearningElement",
        elementId: 28,
        elementName: "l_h5p_drawingtable_2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_drawingtable_2",
      },
      {
        $type: "LearningElement",
        elementId: 29,
        elementName: "l_h5p_daylightprojector_1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_daylightprojector_1",
      },
    ],
  },
};

export default LEModelTestAWT;
