import AWT from "../Types/AWT";

/* istanbul ignore next */
const NewWorldAWT: AWT = {
  fileVersion: "0.4",
  amgVersion: "1.0.0",
  author: "Paul Erhard",
  language: "de",
  world: {
    worldName: "New World",
    worldDescription: "Alle Funktionen in AdLer sind erfolgreich absolvierbar",
    worldGoals: [""],
    topics: [],
    spaces: [
      {
        spaceId: 1,
        spaceName: "Lernraum Bilder",
        spaceDescription: "",
        spaceGoals: [""],
        spaceSlotContents: [1, 2, 3, 4, null, null],
        requiredPointsToComplete: 2,
        requiredSpacesToEnter: "",
        spaceTemplate: "R_20X20_6L",
        spaceTemplateStyle: "Campus",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
      {
        spaceId: 2,
        spaceName: "Lernraum Videos",
        spaceDescription: "",
        spaceGoals: [""],
        spaceSlotContents: [5, 6, 7, null, null, null],
        requiredPointsToComplete: 0,
        requiredSpacesToEnter: "1",
        spaceTemplate: "R_20X20_6L",
        spaceTemplateStyle: "Arcade",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
      {
        spaceId: 3,
        spaceName: "Lernraum h5p",
        spaceDescription: "",
        spaceGoals: [""],
        spaceSlotContents: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
        requiredPointsToComplete: 1,
        requiredSpacesToEnter: "(5)v(4)",
        spaceTemplate: "L_32X31_10L",
        spaceTemplateStyle: "Suburb",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
      {
        spaceId: 4,
        spaceName: "Lernraum Random",
        spaceDescription: "",
        spaceGoals: [""],
        spaceSlotContents: [18, null, null, null, null, 19, null, 20],
        requiredPointsToComplete: 0,
        requiredSpacesToEnter: "2",
        spaceTemplate: "R_20X30_8L",
        spaceTemplateStyle: "Suburb",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
      {
        spaceId: 5,
        spaceName: "Lernraum Random 2",
        spaceDescription: "",
        spaceGoals: [""],
        spaceSlotContents: [null, 21, null, 22, null, 23],
        requiredPointsToComplete: 0,
        requiredSpacesToEnter: "(1)",
        spaceTemplate: "R_20X20_6L",
        spaceTemplateStyle: "Suburb",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
    ],
    elements: [
      {
        $type: "LearningElement",
        elementId: 1,
        elementName: "Bild1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_sciencebio_1",
      },
      {
        $type: "LearningElement",
        elementId: 2,
        elementName: "Bild2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "jpg",
        elementMaxScore: 1,
        elementModel: "l_image_sciencegeo_1",
      },
      {
        $type: "LearningElement",
        elementId: 3,
        elementName: "Bild3(1)",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "webp",
        elementMaxScore: 1,
        elementModel: "l_image_sciencewhiteboard_1",
      },
      {
        $type: "LearningElement",
        elementId: 4,
        elementName: "Bild4(1)",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "jpeg",
        elementMaxScore: 1,
        elementModel: "l_h5p_daylightprojector_1",
      },
      {
        $type: "LearningElement",
        elementId: 5,
        elementName: "YouTube",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l-h5p-blackslotmachine-1",
      },
      {
        $type: "LearningElement",
        elementId: 6,
        elementName: "Vimeo",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l-h5p-purpleslotmachine-1",
      },
      {
        $type: "LearningElement",
        elementId: 7,
        elementName: "TH AB",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 8,
        elementName: "\u00DCbung1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 9,
        elementName: "\u00DCbung2",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 10,
        elementName: "\u00DCbung3",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 11,
        elementName: "\u00DCbung4",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 12,
        elementName: "\u00DCbung5",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 13,
        elementName: "\u00DCbung6",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 14,
        elementName: "\u00DCbung7",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 15,
        elementName: "\u00DCbung8",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 16,
        elementName: "\u00DCbung9",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 17,
        elementName: "\u00DCbung10",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 18,
        elementName: "Bild3(2)",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
      {
        $type: "LearningElement",
        elementId: 19,
        elementName: "Video4(1)",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
      {
        $type: "LearningElement",
        elementId: 20,
        elementName: "Text1",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
      {
        $type: "LearningElement",
        elementId: 21,
        elementName: "H5P11",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
      {
        $type: "LearningElement",
        elementId: 22,
        elementName: "Video4(2)",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
      {
        $type: "LearningElement",
        elementId: 23,
        elementName: "Bild4(2)",
        elementDescription: "",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "webp",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
    ],
  },
};

export default NewWorldAWT;
