import AWT from "../Types/AWT";

/*
 * Showcase-Lernwelt - Basierend auf ATF_Document.json
 */
const ShowcaseWorldAWT: AWT = {
  fileVersion: "2.3.0",
  amgVersion: "2.2.1",
  author: "Antonia Dörringer, Daniel Glaab, Lukas Schaab",
  language: "de",
  world: {
    worldName: "AdLer Demo Welt",
    worldDescription:
      "Dieser Workshop soll Interessierten eine Einführung und einen Überblick über das Projekt AdLer geben.",
    worldGoals: [
      "Die Autorinnen und Autoren können eigenständig eine 3D-Lernwelt erstellen,",
      "indem sie die verschiedenen Funktionen des AdLer-Autorentools nutzen,",
      "um die Lernwelt im Sinne der Motivationsförderung in ihrer Hochschullehre verwenden zu können.",
    ],
    theme: "CampusAschaffenburg",
    evaluationLink: "",
    topics: [],
    spaces: [
      {
        spaceId: 1,
        spaceName: "Vorgeschichte",
        spaceDescription:
          "Unser Lukas muss sich einigen Herausforderungen stellen...",
        requiredPointsToComplete: 1,
        spaceSlotContents: [null, 1, null, null, null, null],
        requiredSpacesToEnter: "",
        spaceGoals: [],
        spaceTemplate: "R_20X20_6L",
        spaceTemplateStyle: "CampusAschaffenburg",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Hallo liebe Gäste!\nMein Name ist Lukas.\nIch möchte Ihnen heute das Projekt AdLer und seine beiden Anwendungen näher bringen.",
              "Zuerst blicken wir in die Vergangenheit. Erwarten Sie Dramatik und Spannung in unserem kurzen Einführungsvideo!",
              "Laufen Sie gerne durch den Raum und erkunden Sie diesen genauer. Das tun Sie mit einem Klick, an die Stelle, zu der Ihr Avatar laufen soll.",
              'Über den Menü Button, im oberen linken Eck der Anwendung, können Sie sich mit dem Button "Steuerung" einen Überblick über diese machen. ',
              "Laufen Sie doch einmal zum gelb leuchtenden Fernseher. Sobald dieser orange leuchtet, können Sie ihn per Mausklick auswählen und den verknüpften Videoinhalt ansehen.",
              "Falls Sie in Ihrer Farbsicht eingeschränkt sind, achten Sie einfach auf die Veränderung der Umrandung der Lernelemente. Diese geschieht, wenn Sie nah genug an einem Element stehen.",
              'Und jetzt: Viel Spaß mit der AdLer 3D-Lernumgebung!\nUm diese Unterhaltung zu beenden, klicken Sie auf den Button: "Danke und mach\'s gut!"',
            ],
            elementModel: "a-npc-teama-male",
          },
          outroStory: {
            storyTexts: [
              'So, das war nun ein kurzer Blick in die Vergangenheit. Es gibt einiges zu tun, aber wie ich im Video bereits sagte: "...das schaffen wir!". ',
              "Ich wünschte, ich könnte auch bereits einen Blick in eine Glaskugel wagen, um zu schauen, ob ich bei Ihnen im Anschluss an unsere Veranstaltung in zufriedene, freudig erregte oder gelangweilte Gesichter schaue...",
              "Wir werden sehen! Nun auf zu den nächsten Räumen!\nUm zu diesen zu gelangen, bewegen Sie Ihren Avatar zur nun geöffneten, roten Ausgangstür und wählen diese dann per Mausklick aus. Daraufhin, erscheint ein Fenster, in welchem Sie den nun freigeschalteten nächsten Raum auswählen können.",
              "Sie haben den Überblick verloren, weil ihnen alles zu nah heran gezoomt ist? Versuchen Sie einmal mithilfe des Mausrads oder der Scrollgeste auf Ihrem Trackpad oder Mobilgerät die Kamera weiter vom Raum zu entfernen. So finden Sie sich sicher schnell zurecht.",
            ],
            elementModel: "a-npc-teama-male",
          },
        },
      },
      {
        spaceId: 2,
        spaceName: "Vorstellung von AdLer im Allgemeinen",
        spaceDescription:
          "Erhalten eines Überblicks über das gesamte Projekt AdLer und seiner Mitwirkenden.",
        requiredPointsToComplete: 4,
        spaceSlotContents: [2, null, 3, null, null, 5, 6, null],
        requiredSpacesToEnter: "1",
        spaceGoals: [
          "Die Autorinnen und Autoren können das AdLer-Projekt hinsichtlich seiner administrativen Struktur und der Inhalte beschreiben.",
        ],
        spaceTemplate: "R_20X30_8L",
        spaceTemplateStyle: "CampusAschaffenburg",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Wo fange ich bei der Vorstellung von AdLer denn nur an? Nun vielleicht bei grundsätzlichen Informationen! Warum haben wir das Projekt, im Jahr 2022, überhaupt gestartet? Was war unsere Motivation und welche Ziele möchten wir mit AdLer erreichen?",
              'Ach ja, und vielleicht sollte ich auch erwähnen, wer "Wir" sind, wenn ich von „Wir“ spreche.',
              "Nun! Lasst uns loslegen!",
            ],
            elementModel: "a-npc-teama-male",
          },
          outroStory: null,
        },
      },
      {
        spaceId: 3,
        spaceName: "Autorentool",
        spaceDescription: "Was ist das Autorentool und wie ist es aufgebaut?",
        requiredPointsToComplete: 9,
        spaceSlotContents: [7, 8, 9, 10, 11, 12, 13, 14, 15, null],
        requiredSpacesToEnter: "2",
        spaceGoals: [
          "Die Autorinnen und Autoren können das AdLer-Projekt hinsichtlich seiner administrativen Struktur und der Inhalte beschreiben.                ",
        ],
        spaceTemplate: "L_32X31_10L",
        spaceTemplateStyle: "CampusKempten",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Wir kommen nun zum ersten Tool, das im Rahmen des Projekts entstanden ist.",
              "Ich muss gestehen, ich bin etwas nervös, da ich zwar das Tool vorstelle, selbst aber gar nicht daran mitgewirkt habe.",
              "Das Autorentool ermöglicht Lehrpersonen ihre Inhalte in einer nutzendenfreundlichen Umgebung in Lernelementen und Lernräumen innerhalb einer Lernwelt in Form zu bringen.",
              "Ich wünsche Ihnen viel Spaß beim erkunden!",
            ],
            elementModel: "a-npc-teama-male",
          },
          outroStory: null,
        },
      },
      {
        spaceId: 4,
        spaceName: "Moodle und 3D-Lernumgebung",
        spaceDescription:
          "Was ist die 3D-Lernumgebung und wie ist sie aufgebaut?",
        requiredPointsToComplete: 8,
        spaceSlotContents: [
          16,
          null,
          17,
          18,
          null,
          19,
          20,
          null,
          21,
          22,
          null,
          23,
          null,
        ],
        requiredSpacesToEnter: "2",
        spaceGoals: [
          "Die Autorinnen und Autoren können die Möglichkeiten der 3D-Darstellung eines Lernraums beschreiben,\num bei der zukünftigen Gestaltung einer eigenen Lernwelt im Autorentool fundierte Entscheidungen treffen zu können.",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "Suburb",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Nun zum zweiten Tool, das im Rahmen des Projekts entstanden ist.",
              "Verzeiht mir meine Aufgregung, aber als Mitglied des Teams, das sich in den vergangenen Jahren intensiv mit der Erstellung dieses Tools beschäftigt hat, geht mir einfach das Herz auf, wenn ich darüber berichten darf.",
              "Der Raum befasst sich außerdem mit der Anbindung an unser AdLer-LMS (Learning Management System) - Moodle.",
              "Mit dieser Anbindung ist es uns möglich ein Duplikat des im Autorentool erstellten Kurses, auch auf einem LMS in dessen Oberfläche anzubieten.",
              "Aber sehen Sie selbst!",
            ],
            elementModel: "a-npc-teama-male",
          },
          outroStory: null,
        },
      },
      {
        spaceId: 5,
        spaceName: "Abschluss",
        spaceDescription:
          "Das AdLer Team kommt zum Jour fixe zusammen und Lukas präsentiert den Inhalt des Workshops.",
        requiredPointsToComplete: 1,
        spaceSlotContents: [null, null, null, 24, null, null],
        requiredSpacesToEnter: "(3)^(4)",
        spaceGoals: [],
        spaceTemplate: "R_20X20_6L",
        spaceTemplateStyle: "Arcade",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Es war mir eine Freude, Ihnen das Projekt AdLer vorzustellen.",
              "Ich glaube, ich deute ihre Blicke richtig und sehe entzückte Gesichter. \nWie schön! Glückliche Gäste - glücklicher Gastgeber.",
              "Ich hoffe Sie konnten vieles aus dieser kleinen Vorstellung unseres Projekts mitnehmen.\nWir sind sehr stolz auf das was wir geschaffen haben und freuen uns darauf, dass der AdLer in Zukunft in der Lehre eingesetzt wird.",
              "Gehaben Sie sich wohl und herzlichsten Dank für Ihren Besuch!",
            ],
            elementModel: "a-npc-teama-male",
          },
          outroStory: null,
        },
      },
    ],
    elements: [
      {
        $type: "LearningElement",
        elementId: 1,
        elementName: "Was zuvor geschah",
        elementDescription:
          "Projektleiter Jörg hat alle Hände voll zu tun und bittet Lukas um Hilfe.",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
      {
        $type: "LearningElement",
        elementId: 2,
        elementName: "Projektname",
        elementDescription:
          "Grafische Darstellung des AdLer Logos und AdLer Schriftzugs",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "jpg",
        elementMaxScore: 1,
        elementModel: "l_picture_paintingeasel_1",
      },
      {
        $type: "LearningElement",
        elementId: 3,
        elementName: "Thema und Ziele",
        elementDescription:
          "Interaktives Lernelement mit verschiedenen Folien und einer Abschlussfrage.",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_daylightprojector_1",
      },
      {
        $type: "LearningElement",
        elementId: 5,
        elementName: "Standorte",
        elementDescription:
          "Deutschlandkarte mit den eingezeichneten Standorten der Verbundpartner.",
        elementGoals: [""],
        elementCategory: "pdf",
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_text_comicshelfsmall_1",
      },
      {
        $type: "LearningElement",
        elementId: 6,
        elementName: "Team",
        elementDescription:
          "Foto des AdLer Teams beim Verbundtreffen im Mai 2023.",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "jpg",
        elementMaxScore: 1,
        elementModel: "l_image_sciencebio_1",
      },
      {
        $type: "LearningElement",
        elementId: 7,
        elementName: "Lernwelt Allgemeines",
        elementDescription:
          "In diesem Bild wird erklärt, was im Rahmen des AdLer-\nProjekts unter Lernwelten verstanden wird.",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_image_sciencegeo_1",
      },
      {
        $type: "LearningElement",
        elementId: 8,
        elementName: "Lernwelt",
        elementDescription:
          "In diesem interaktiven Lernelement wird der Aufbau des Autorentools zur Erstellung einer Lernwelt vorgestellt.",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_deskpc_3",
      },
      {
        $type: "LearningElement",
        elementId: 9,
        elementName: "Lernraum - Allgemeines",
        elementDescription:
          "Das Video erklärt die Bedeutung von Lernräumen und welche charakteristischen Eigenschaften diesen zugeschrieben werden können.",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_television_1",
      },
      {
        $type: "LearningElement",
        elementId: 10,
        elementName: "Lernraum - Lernpfad",
        elementDescription:
          "Mit diesem Bild werden verschiedene mögliche Wege der Zielerreichung gezeigt.",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "png",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackboard_2",
      },
      {
        $type: "LearningElement",
        elementId: 11,
        elementName: "Lernraum - Lernziele",
        elementDescription:
          "Dieses Video erklärt den Aufbau der Eingabeunterstützung, die im Autorentool für das Formulieren von Lernzielen bereitgestellt wird.",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_movieprojector_1",
      },
      {
        $type: "LearningElement",
        elementId: 12,
        elementName: "Lernraum - Grundrisse",
        elementDescription:
          "In diesem Video wird der Aufbau von Grundrissen vorgestellt und welchen Nutzen diese haben.",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_television_1",
      },
      {
        $type: "LearningElement",
        elementId: 13,
        elementName: "Storyelement",
        elementDescription:
          "In diesem PDF wird das Storyelement vorgestellt, mit welchem das Erzählen einer Geschichte innerhalb einer Lernwelt ermöglicht wird.",
        elementGoals: [""],
        elementCategory: "pdf",
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_h5p_daylightprojector_1",
      },
      {
        $type: "LearningElement",
        elementId: 14,
        elementName: "Lernelement",
        elementDescription:
          "In diesem PDF werden die Lernelemente thematisiert, welche die Möglichkeit bieten, Lernenden unterschiedliche multimediale Inhalte bereitzustellen.",
        elementGoals: [""],
        elementCategory: "pdf",
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_text_libraryshelf_1",
      },
      {
        $type: "LearningElement",
        elementId: 15,
        elementName: "Adaptivitätselement",
        elementDescription:
          "Dieser Text stellt das Adaptivitätselement vor, mit welchem individuelles Lernen ermöglicht werden soll.",
        elementGoals: [""],
        elementCategory: "pdf",
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_text_libraryshelf_1",
      },
      {
        $type: "LearningElement",
        elementId: 16,
        elementName: "Darstellung Lernpfad",
        elementDescription:
          "Informationsfolie zur Darstellung der Lernpfade innerhalb des Menüs der 3D-Umgebung.",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "jpg",
        elementMaxScore: 1,
        elementModel: "l_image_sciencewhiteboard_1",
      },
      {
        $type: "LearningElement",
        elementId: 17,
        elementName: "Story Element",
        elementDescription:
          "Informationsfolie zu Story Elementen in der 3D-Umgebung.",
        elementGoals: [""],
        elementCategory: "pdf",
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_text_comicshelfbig_1",
      },
      {
        $type: "LearningElement",
        elementId: 18,
        elementName: "Moodle",
        elementDescription:
          "Informationstext zur Anzeige von Inhalten von AdLer im LMS - Moodle.",
        elementGoals: [""],
        elementCategory: "text",
        elementFileType: "txt",
        elementMaxScore: 1,
        elementModel: "l_text_bookshelf_2",
      },
      {
        $type: "LearningElement",
        elementId: 19,
        elementName: "3D-Lernumgebung",
        elementDescription:
          "Prüfen Sie ihr wissen zur 3D-Lernumgebung in diesem interaktiven Quiz.",
        elementGoals: [""],
        elementCategory: "h5p",
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_deskpc_3",
      },
      {
        $type: "LearningElement",
        elementId: 20,
        elementName: "Lernziele",
        elementDescription:
          "Informationsfolie zur Darstellung von Lernzielen in der 3D-Umgebung.",
        elementGoals: [""],
        elementCategory: "image",
        elementFileType: "jpg",
        elementMaxScore: 1,
        elementModel: "l_image_sciencewhiteboard_1",
      },
      {
        $type: "LearningElement",
        elementId: 21,
        elementName: "Grundrisse Themes Avatar und 3D",
        elementDescription:
          "Videopräsentation mit einer Auflistung der verschiedenen Grundrisse der AdLer Anwendungen. Außerdem werden verschiedene Themes und der Avatar gezeigt.",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_vrdesk_1",
      },
      {
        $type: "LearningElement",
        elementId: 22,
        elementName: "Lernelemente",
        elementDescription:
          "Informationsfolie zur Darstellung von Lernelementen in der 3D-Umgebung.",
        elementGoals: [""],
        elementCategory: "pdf",
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_random",
      },
      {
        $type: "LearningElement",
        elementId: 23,
        elementName: "3D-Umgebung Adaptivitätselement",
        elementDescription:
          "Informationsfolie zur Funktion und Darstellung des Adaptivitätselements in der 3D-Umgebung.",
        elementGoals: [""],
        elementCategory: "pdf",
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_text_comicshelfsmall_1",
      },
      {
        $type: "LearningElement",
        elementId: 24,
        elementName: "Vielen Dank",
        elementDescription:
          "Es ist Mittwoch. Das Jour fixe steht an. Das Team AdLer Aschaffenburg ist zusammengekommen, um Lukas bei dessen Präsentation zu lauschen.",
        elementGoals: [""],
        elementCategory: "video",
        elementFileType: "url",
        elementMaxScore: 1,
        elementModel: "l_video_movieprojector_1",
      },
    ],
  },
};

export default ShowcaseWorldAWT;
