import AWT from "../Types/AWT";
import { MockAdaptivityData } from "./MockAdaptivityData";

/* istanbul ignore next */
const SimpleWorldAWT: AWT = {
  fileVersion: "0.4",
  amgVersion: "1.0",
  author: "Ricardo",
  language: "de",
  world: {
    worldName: "Simple World",
    worldDescription: "",
    worldGoals: [""],
    theme: "CampusAschaffenburg",
    evaluationLink: "https://www.th-ab.de",
    evaluationLinkName: "50 Zeichen: This is a test name. MMWWMWMWMMWMMWWMM",
    evaluationLinkText:
      "200 Zeichen: MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMMWMWMWMWMWMWMWMWMWMWMWMMWMWMMWMWM",
    topics: [
      {
        topicId: 7,
        topicName: "Themenbereich der kleinen Welt",
        topicContents: [1],
      },
    ],
    spaces: [
      {
        spaceId: 1,
        spaceName: "Lernelemente Demo-Raum",
        spaceDescription:
          "Demonstrationsraum mit allen Standard-Lernelementtypen",
        requiredPointsToComplete: 3,
        spaceSlotContents: [1, 2, 3, 4, 5, 6, 7, 8, 9, null, null, null, null],
        requiredSpacesToEnter: "",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "CampusMensa",
        spaceStory: {
          introStory: {
            storyTexts: ["Test1."],
            elementModel: "a-npc-defaultlight-male",
            modelFacialExpression: "happy",
            storyNpcName: "Yoda",
            exitAfterStorySequence: true,
          },
          outroStory: {
            storyTexts: ["Test1."],
            elementModel: "a-npc-defaultlight-male",
            modelFacialExpression: "happy",
            storyNpcName: "Yoda",
            exitAfterStorySequence: true,
          },
        },
      },
    ],
    elements: [
      {
        $type: "LearningElement",
        elementId: 1,
        elementName: "Das Text-Lernelement",
        elementCategory: "text",
        elementDescription: "Beschreibung des Text-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "text",
        elementMaxScore: 9,
        elementModel: "l_trophy_bronze",
        elementDifficulty: 200,
        elementEstimatedTimeInMinutes: 10,
      },
      {
        $type: "LearningElement",
        elementId: 2,
        elementName: "Ein Video-Lernelement",
        elementCategory: "video",
        elementDescription: "Beschreibung des Video-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "video",
        elementMaxScore: 2,
        elementModel: "l-video-vrdesk-1",
        elementDifficulty: 100,
        elementEstimatedTimeInMinutes: 5,
      },
      {
        $type: "LearningElement",
        elementId: 3,
        elementName: "Ein Bild-Lernelement",
        elementCategory: "image",
        elementDescription: "Beschreibung des Bild-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "image",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "AdaptivityElement",
        elementId: 4,
        elementName: "Ein Adaptivitäts-Lernelement",
        elementCategory: "adaptivity",
        elementDescription: "Beschreibung des Adaptivitäts-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "text",
        elementMaxScore: 1,
        elementModel: "",
        adaptivityContent: MockAdaptivityData,
      },
      {
        $type: "BaseLearningElement",
        elementId: 999,
        elementName: "Hier steht ein externes Lernelement",
        elementCategory: "text",
        elementFileType: "text",
      },
      {
        $type: "LearningElement",
        elementId: 5,
        elementName: "Multiple Choice Demo",
        elementCategory: "h5p",
        elementDescription: "Ein Multiple Choice Quiz - klicke auf 'richtig'",
        elementGoals: [
          "Multiple Choice Funktionalität testen",
          "Einfache Auswahl treffen",
        ],
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackboard_1",
        elementDifficulty: 30,
        elementEstimatedTimeInMinutes: 1,
      },
      {
        $type: "LearningElement",
        elementId: 6,
        elementName: "Ein PDF-Lernelement",
        elementCategory: "pdf",
        elementDescription: "Beschreibung des PDF-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_h5p_drawingtable_2", // should load correct model via compability lookup table
      },
      {
        $type: "LearningElement",
        elementId: 8,
        elementName: "Ein zweites PDF-Lernelement",
        elementCategory: "pdf",
        elementDescription: "Beschreibung des PDF-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l-h5p-drawingtable-2", //should load correct model natively
      },
      {
        $type: "LearningElement",
        elementId: 7,
        elementName: "Ein zweites Video-Lernelement",
        elementCategory: "video",
        elementDescription: "Beschreibung des Video-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "video",
        elementMaxScore: 2,
        elementModel: "l_video_vrdesk_1",
      },
      {
        $type: "LearningElement",
        elementId: 9,
        elementName: "Primitives H5P Quiz",
        elementCategory: "primitiveH5P",
        elementDescription: "Ein einfaches H5P-Quiz für Tests",
        elementGoals: ["H5P Funktionalität testen", "Primitives Quiz lösen"],
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackboard_2",
        elementDifficulty: 25,
        elementEstimatedTimeInMinutes: 2,
      },
    ],
  },
};

export default SimpleWorldAWT;
