import AWT from "../Types/AWT";
import { MockAdaptivityData } from "./MockAdaptivityData";

/* istanbul ignore next */
const SimpleWorldAWT: AWT = {
  fileVersion: "0.4",
  amgVersion: "1.0",
  author: "Ricardo",
  language: "de",
  world: {
    worldName: "Simple World",
    worldDescription: "",
    worldGoals: [""],
    evaluationLink: "https://www.th-ab.de",
    topics: [
      {
        topicId: 7,
        topicName: "Themenbereich der kleinen Welt",
        topicContents: [1],
      },
    ],
    spaces: [
      {
        spaceId: 1,
        spaceName: "Mensa Theme",
        spaceDescription: "Raumbeschreibung der kleinen Welt",
        requiredPointsToComplete: 3,
        spaceSlotContents: [
          1,
          2,
          3,
          4,
          null,
          5,
          null,
          6,
          null,
          null,
          null,
          null,
          null,
        ],
        requiredSpacesToEnter: "",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "CampusMensa",
        spaceStory: {
          introStory: null,
          outroStory: null,
        },
      },
    ],
    elements: [
      {
        $type: "LearningElement",
        elementId: 1,
        elementName: "Das Text-Lernelement",
        elementCategory: "text",
        elementDescription: "Beschreibung des Text-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "text",
        elementMaxScore: 1,
        elementModel: "l_trophy_bronze",
        elementDifficulty: 200,
      },
      {
        $type: "LearningElement",
        elementId: 2,
        elementName: "Ein Video-Lernelement",
        elementCategory: "video",
        elementDescription: "Beschreibung des Video-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "video",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 3,
        elementName: "Ein Bild-Lernelement",
        elementCategory: "image",
        elementDescription: "Beschreibung des Bild-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "image",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "AdaptivityElement",
        elementId: 4,
        elementName: "Ein Adaptivitäts-Lernelement",
        elementCategory: "adaptivity",
        elementDescription: "Beschreibung des Adaptivitäts-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "text",
        elementMaxScore: 1,
        elementModel: "",
        adaptivityContent: MockAdaptivityData,
      },
      {
        $type: "BaseLearningElement",
        elementId: 999,
        elementName: "Hier steht ein externes Lernelement",
        elementCategory: "text",
        elementFileType: "text",
      },
      {
        $type: "LearningElement",
        elementId: 5,
        elementName: "Ein H5P-Lernelement",
        elementCategory: "primitiveH5P",
        elementDescription: "Beschreibung des H5P-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackboard_1",
      },
      {
        $type: "LearningElement",
        elementId: 6,
        elementName: "Ein PDF-Lernelement",
        elementCategory: "pdf",
        elementDescription: "Beschreibung des PDF-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_h5p_drawingtable_2",
      },
    ],
  },
};

export default SimpleWorldAWT;
