import AWT from "../Types/AWT";
import { MockAdaptivityData } from "./MockAdaptivityData";

/* istanbul ignore next */
const SmallWorldAWT: AWT = {
  fileVersion: "0.4",
  amgVersion: "1.0",
  author: "Ricardo",
  language: "de",
  world: {
    worldName: "Theme World",
    worldDescription:
      "Small World with only one topic and one space but with all elements",
    worldGoals: ["Weltziel 1/3", "Weltziel 2/3", "Weltziel 3/3"],
    evaluationLink: "https://www.th-ab.de",
    topics: [
      {
        topicId: 7,
        topicName: "Themenbereich der kleinen Welt",
        topicContents: [1],
      },
    ],
    spaces: [
      {
        spaceId: 1,
        spaceName: "Mensa Theme",
        spaceDescription: "Raumbeschreibung der kleinen Welt",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          1,
          2,
          3,
          4,
          null,
          5,
          null,
          6,
          null,
          null,
          null,
          null,
          null,
        ],
        requiredSpacesToEnter: "",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "CampusMensa",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod ",
            ],
            elementModel: "a-quizbg-defaultnpc",
          },
          outroStory: {
            storyTexts: ["Tschüss", "Du bist mit diesem Raum fertig"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 2,
        spaceName: "Library Theme",
        spaceDescription: "Raumbeschreibung der kleinen Welt",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          1,
          2,
          3,
          4,
          null,
          5,
          null,
          6,
          null,
          null,
          null,
          null,
          null,
        ],
        requiredSpacesToEnter: "1",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ",
        ],

        spaceTemplate: "D_40X37_15L",
        spaceTemplateStyle: "CampusLibrary",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod ",
            ],
            elementModel: "a-quizbg-defaultnpc",
          },
          outroStory: {
            storyTexts: ["Tschüss", "Du bist mit diesem Raum fertig"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 3,
        spaceName: "Campus Kempten Theme",
        spaceDescription: "Raumbeschreibung der kleinen Welt",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          1,
          2,
          3,
          4,
          null,
          5,
          null,
          6,
          null,
          null,
          null,
          null,
          null,
        ],
        requiredSpacesToEnter: "2",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "CAMPUSKEMPTEN",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod ",
            ],
            elementModel: "a-quizbg-defaultnpc",
          },
          outroStory: {
            storyTexts: ["Tschüss", "Du bist mit diesem Raum fertig"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 4,
        spaceName: "Campus Aschaffenburg Theme",
        spaceDescription: "Raumbeschreibung der kleinen Welt",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          1,
          2,
          3,
          4,
          null,
          5,
          null,
          6,
          null,
          null,
          null,
          null,
          null,
        ],
        requiredSpacesToEnter: "3",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "CampusAB",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod ",
            ],
            elementModel: "a-quizbg-defaultnpc",
          },
          outroStory: {
            storyTexts: ["Tschüss", "Du bist mit diesem Raum fertig"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 5,
        spaceName: "Suburb Theme",
        spaceDescription: "Raumbeschreibung der kleinen Welt",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          1,
          2,
          3,
          4,
          null,
          5,
          null,
          6,
          null,
          null,
          null,
          null,
          null,
        ],
        requiredSpacesToEnter: "4",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "Suburb",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod ",
            ],
            elementModel: "a-quizbg-defaultnpc",
          },
          outroStory: {
            storyTexts: ["Tschüss", "Du bist mit diesem Raum fertig"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
      {
        spaceId: 6,
        spaceName: "Arcade Theme",
        spaceDescription: "Raumbeschreibung der kleinen Welt",
        requiredPointsToComplete: 0,
        spaceSlotContents: [
          1,
          2,
          3,
          4,
          null,
          5,
          null,
          6,
          null,
          null,
          null,
          null,
          null,
        ],
        requiredSpacesToEnter: "5",
        spaceGoals: [
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ",
        ],
        spaceTemplate: "T_40X32_13L",
        spaceTemplateStyle: "Arcade",
        spaceStory: {
          introStory: {
            storyTexts: [
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod sto ",
            ],
            elementModel: "a-quizbg-defaultnpc",
          },
          outroStory: {
            storyTexts: ["Tschüss", "Du bist mit diesem Raum fertig"],
            elementModel: "a_npc_defaultnpc",
          },
        },
      },
    ],
    elements: [
      {
        $type: "LearningElement",
        elementId: 1,
        elementName: "Ein Text-Lernelement",
        elementCategory: "text",
        elementDescription: "Beschreibung des Text-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "text",
        elementMaxScore: 1,
        elementModel: "l_trophy_bronze",
      },
      {
        $type: "LearningElement",
        elementId: 2,
        elementName: "Ein Video-Lernelement",
        elementCategory: "video",
        elementDescription: "Beschreibung des Video-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "video",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "LearningElement",
        elementId: 3,
        elementName: "Ein Bild-Lernelement",
        elementCategory: "image",
        elementDescription: "Beschreibung des Bild-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "image",
        elementMaxScore: 1,
        elementModel: "",
      },
      {
        $type: "AdaptivityElement",
        elementId: 4,
        elementName: "Ein Adaptivitäts-Lernelement",
        elementCategory: "adaptivity",
        elementDescription: "Beschreibung des Adaptivitäts-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "text",
        elementMaxScore: 1,
        elementModel: "",
        adaptivityContent: MockAdaptivityData,
      },
      {
        $type: "BaseLearningElement",
        elementId: 999,
        elementName: "Hier steht ein externes Lernelement",
        elementCategory: "text",
        elementFileType: "text",
      },
      {
        $type: "LearningElement",
        elementId: 5,
        elementName: "Ein H5P-Lernelement",
        elementCategory: "primitiveH5P",
        elementDescription: "Beschreibung des H5P-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "h5p",
        elementMaxScore: 1,
        elementModel: "l_h5p_blackboard_1",
      },
      {
        $type: "LearningElement",
        elementId: 6,
        elementName: "Ein PDF-Lernelement",
        elementCategory: "pdf",
        elementDescription: "Beschreibung des PDF-Lernelements",
        elementGoals: ["Elementziel 1/3", "Elementziel 2/3", "Elementziel 3/3"],
        elementFileType: "pdf",
        elementMaxScore: 1,
        elementModel: "l_h5p_drawingtable_2",
      },
    ],
  },
};

export default SmallWorldAWT;
