import IOveralTimeSpentNotificationController from "./IOverallTimeSpentAdaptivityNotificationController";

export default class OveralTimeSpentNotificationController
  implements IOveralTimeSpentNotificationController {}
