import IOverallTimeSpentAdaptivityNotificationController from "./IOverallTimeSpentAdaptivityNotificationController";

export default class OverallTimeSpentAdaptivityNotificationController
  implements IOverallTimeSpentAdaptivityNotificationController {}
