import IOveralTimeSpentAdaptivityNotificationController from "./IOverallTimeSpentAdaptivityNotificationController";

export default class OveralTimeSpentAdaptivityNotificationController
  implements IOveralTimeSpentAdaptivityNotificationController {}
