import IOveralTimeSpentNotificationController from "./IOveralTimeSpentNotificationController";

export default class OveralTimeSpentNotificationController
  implements IOveralTimeSpentNotificationController {}
