# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# https://stackoverflow.com/a/73060319
name: test and build

on:
  workflow_call:
    secrets:
      COVERALLS_REPO_TOKEN:
        description: coveralls token
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test-ci

      - name: Coveralls upload
        continue-on-error: true
        if: github.ref == 'refs/heads/main'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run coveralls

      - name: NPM build
        run: npm run build --if-present

      - name: upload build folder for reuse in next job
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
          retention-days: 7

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@v2.3.0
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
