name: Build, test, containerize and push to registry

on:
  push:
    branches:
      - "main"

jobs:
  build:
    uses: ./.github/workflows/_shared_build_test.yml
    secrets: inherit

  docker:
    needs: build
    uses: ./.github/workflows/_shared_docker.yml
