name: Build, test, containerize and push to registry

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/_shared_build_test.yml
    secrets: inherit

  docker:
    needs: build
    uses: ./.github/workflows/_shared_docker.yml

  discord_notification:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare release body (description)
        id: prep_body
        run: |
          echo "${{ github.event.release.body }}" > changes.md

      - name: Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_RELEASE_CHANNEL_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_RELEASE_CHANNEL_WEBHOOK_TOKEN }}
          username: GitHub Releases
          message: "New release of **${{ github.repository }}**\nVersion: ${{ github.ref_name }} (${{github.event.release.name}})\n<${{ github.event.release.html_url }}>"
          file: changes.md