name: Build, test, containerize and push to registry

on:
  release:
    types: [created]
  push:
    branches:
      - "main"
      - "georg202306"

jobs:
  build:
    uses: ./.github/workflows/_shared_build_test.yml
    secrets: inherit

  docker:
    needs: build
    uses: ./.github/workflows/_shared_docker.yml
